// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 3
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){













var db=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var eb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,fb=function(a){if(null==a)return String(a);var b=eb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},gb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Pa=function(a){if(!a||"object"!=fb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!gb(a,"constructor")&&!gb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||gb(a,b)},hb=function(a,b){var c=b||("array"==fb(a)?[]:{}),d;for(d in a)if(gb(a,d)){var e=a[d];"array"==fb(e)?("array"!=fb(c[d])&&(c[d]=[]),c[d]=hb(e,c[d])):Pa(e)?(Pa(c[d])||(c[d]={}),c[d]=hb(e,c[d])):c[d]=e}return c};var Ta=null,ib=Math.random(),jb=null,Ia=null,ab=!1,kb={},lb={},cb={};var mb,nb,ob,pb,qb,rb,sb,tb,vb,wb,xb,yb,S,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Nb,Ob,Pb,Qb,Rb,Sb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,V,gd,hd,id,jd,kd,ld,md,nd,qd,rd,sd,td,ud,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,
Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf;
(function(){var a=function(a){return{toString:function(){return a}}};mb=a("");nb=a("");ob="";pb=a("");qb=a("");rb=a("");sb=a("");tb=a("");vb=a("");wb=a("");xb=a("");yb=a("0");S=a("1");zb=a("");Ab=a("");Bb=a("");
Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Kb=a("");Lb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");
Rb=a("");Sb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("2");Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");
ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("3");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");
zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");
Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("4");ad=a("");bd=a("10");cd=a("11");dd=a("");ed=a("");
fd=a("5");V=a("6");gd=a("");hd=a("");id=a("");jd=a("");kd=a("7");ld=a("");md=a("");nd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");
Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");
Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");
pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("9");Ee=
a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");
Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e="";af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=
a("");nf=a("");of=a("");pf=a("");qf=a("")})();var rf=function(){},P=function(a){return"function"==typeof a},za=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},sf=function(a){return"number"==fb(a)&&!isNaN(a)},tf=function(a){return/^[0-9]+$/.test(a)},uf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Ha=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},N=function(a){return Math.round(Number(a))||0},Ja=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},vf=function(a){var b=[];if(za(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},H=function(){return new Date},Ma=function(a,b){if(!sf(a)||!sf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Bf=function(){this.prefix="gtm.";this.values={}};Bf.prototype.set=function(a,b){this.values[this.prefix+a]=b};Bf.prototype.get=function(a){return this.values[this.prefix+a]};Bf.prototype.contains=function(a){return void 0!==this.get(a)};
var Cf=function(a,b,c){try{if(!a[Fd])return a[$c](a,b||rf,c||rf);c&&c()}catch(d){}return!1},Df=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Ha(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Ef=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Ff=function(a){return function(){return a("GTM-T6RZMX")}},Gf=function(a){for(var b=0;b<a.length;b++)a[b]()},Hf=H().getTime(),Oa=function(){return"gtm"+
Hf++},Qa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},If=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Kf=function(a,b){0==b?a.Wa=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Ha[c]=b);kb[c]&&(kb[c].state=b)},Lf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var w=window,M=document,Nf=navigator,R=function(a,b){var c=w[a];w[a]=void 0===c?b:c;return w[a]},J=function(a,b,c,d){return(d||"http:"!=w.location.protocol?a:b)+c},Of=function(a){var b=M.getElementsByTagName("script")[0]||M.body||M.head;b.parentNode.insertBefore(a,b)},Sa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},q=function(a,b,c){var d=M.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;Sa(d,b);c&&(d.onerror=c);Of(d);return d},ja=function(a,b){var c=M.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Of(c);Sa(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},O=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},x=function(a){w.setTimeout(a,0)},Va=!1,
Wa=[],Pf=function(a){if(!Va){var b=M.createEventObject,c="complete"==M.readyState,d="interactive"==M.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Va=!0;for(var e=0;e<Wa.length;e++)Wa[e]()}Wa.push=function(){for(var a=0;a<arguments.length;a++)x(arguments[a]);return 0}}},Qf=0,Rf=function(){if(!Va&&140>Qf){Qf++;try{M.documentElement.doScroll("left"),Pf()}catch(a){w.setTimeout(Rf,50)}}},Ba=function(a){var b=M.getElementById(a);if(b&&ua(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ua(document.all[a][c],
"id")==a)return document.all[a][c];return b},ua=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},xa=function(a){return a.target||a.srcElement||{}},Ga=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},$a=function(a){var b=M.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},
ya=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Sf=!1,Tf=[],Uf=function(){if(!Sf){Sf=!0;for(var a=0;a<Tf.length;a++)Tf[a]()}},Vf=function(a){a=a||w;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},Xa=function(a){window.console&&window.console.log&&window.console.log(a)};var aa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||w.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||w.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:w.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=uf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var p=l[m].split("=");if(decodeURIComponent(p[0]).replace(/\+/g," ")==e){f=decodeURIComponent(p.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Wf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ba=function(a){var b=
M.createElement("a");a&&(b.href=a);return b};var ka=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ga=function(a,b,c){G(a,b,c)},ia=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=aa(ba(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},Da=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var Xf=new Bf,Yf={},$f={set:function(a,b){hb(Zf(a,b),Yf)},get:function(a){return Q(a,2)},reset:function(){Xf=new Bf;Yf={}}},Q=function(a,b){if(2==b){for(var c=Yf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Xf.get(a)},Zf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var ag=Math.random(),bg="0.100000">ag;var cg=function(a,b){bg&&G("//www.googletagmanager.com/a?id=GTM-T6RZMX&cv=3&v=t&n="+a+(void 0!==b?"&s="+encodeURIComponent(b):"")+"&l="+(H().getTime()-N(jb))+"&sr=0.100000&ps="+ag+"&cb="+Ma());},dg=rf;var eg=rf,fg=[],gg=!1,ca=function(a){return w["dataLayer"].push(a)},hg=function(a){var b=!1;return function(){!b&&P(a)&&x(Ff(a));b=!0}},ng=function(){for(var a=!1;!gg&&0<fg.length;){gg=!0;var b=fg.shift();if(P(b))try{b.call($f)}catch(Aa){}else if(za(b))a:{var c=b;if("string"==fb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Yf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Aa){}}}else{var k=void 0,l=void 0,m=b;for(l in m)if(m.hasOwnProperty(l)){var p=
l,r=m[l];Xf.set(p,r);hb(Zf(p,r),Yf)}var u=!1,y=m.event;if(y){k=Hf++;Ia=y;if(!m["gtm.uniqueEventId"]){var t=k;Xf.set("gtm.uniqueEventId",t);hb(Zf("gtm.uniqueEventId",t),Yf)}var z=hg(m.eventCallback),D=m.eventTimeout;D&&w.setTimeout(z,Number(D));u=eg(k,y,z,m.eventReporter)}jb||(jb=m["gtm.start"])&&dg();var B=m,A=k,E=y,I=Yf;if(!u){var F=k,K=y;}Ia=null;a=u||a}var U=b,L=Yf;mg();gg=!1}return!a},og=function(){var a=ng();try{var b=w["dataLayer"].hide;if(b&&void 0!==b["GTM-T6RZMX"]&&b.end){b["GTM-T6RZMX"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a};var wa=function(a,b,c){O(a,b,c,void 0)},ea=function(a,b,c){q(a,b,c)},fa=function(a,b){w[a]=b},n=function(a,b,c){var d=w;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},v=function(a,b,c,d){return(d||"https:"==w.location.protocol?a:b)+c};var pg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),qg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},rg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},sg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},tg=function(){var a=Q("gtm.whitelist");
var b=a&&sg(vf(a),qg),c=Q("gtm.blacklist")||Q("tagTypeBlacklist")||[];pg.test(w.location&&w.location.hostname)&&(c=vf(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&sg(vf(c),rg),e={};return function(f){var g=f&&f[$c];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>uf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>uf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var l=!1;if(c){var m;if(!(m=0<=uf(d,g.a)))a:{for(var p=g.b||[],r=new Bf,u=0;u<d.length;u++)r.set(d[u],!0);for(u=0;u<p.length;u++)if(r.get(p[u])){m=!0;break a}m=!1}l=m}return e[g.a]=!h||l}};var Fa=function(a){var b=M;return ug?b.querySelectorAll(a):null},vg=!1;if(M.querySelectorAll)try{var wg=M.querySelectorAll(":root");wg&&1==wg.length&&wg[0]==M.documentElement&&(vg=!0)}catch(a){}var ug=vg;var _eu=function(a){var b=String(Q("gtm.elementUrl")||a[xc]||""),c=ba(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ia};_e.a="e";_e.b=["google"];var Bg=/(^|\.)doubleclick\.net$/i,Cg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ka=function(a){for(var b=String(M.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=Ha(e[0]);if(f&&f==a){var g=Ha(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},Dg=function(a,b,c,d,e){if(Bg.test(M.location.hostname)||"/"==c&&Cg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=M.cookie;M.cookie=f;return g!=
M.cookie||0<=uf(Ka(a),b)},Eg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Fg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Gg=function(){var a=aa(w.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Hg=function(a,b){this.f=a;this.j=b};Hg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var Ig=function(a,b){this.Fa=a;this.ka=b};Ig.prototype.toString=function(){return""+this.ka+"."+this.Fa};var Lg=function(a,b){var c=new Jg(null,a,b);Kg(c);return c},Jg=function(a,b,c){this.Oa=Math.floor(H().getTime()/864E5);this.ja=b||"auto";this.aa=c||"/";var d=Eg(this.ja),e=Fg(this.aa);this.F=a||new Hg(d,e);this.h=[];this.C=new Bf},Ng=function(a,b,c){b&&(""==c.Fa?Mg(a,b):(a.C.contains(b)||a.h.push(b),a.C.set(b,c)))},Og=function(a,b){for(var c=0;c<b.length;c++)Ng(a,b[c][0],b[c][1])},Mg=function(a,b){var c=uf(a.h,b);0<=c&&a.h.splice(c,1);a.C.set(b,void 0)},Pg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.C.get(d)])}return b},Qg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.C.get(a.h[c]).ka);return 864E5*b};Jg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.C.get(c).toString())}return"GAX1."+this.F.toString()+"."+a.join("!")};
var Rg=function(a,b){for(var c=new Date,d=Fg(a.aa),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.C.get(g).ka<a.Oa&&e.push(g)}for(f=0;f<e.length;f++)Mg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(Qg(a));if("auto"!=a.ja)return Dg("_gaexp",a.toString(),a.aa,a.ja,c);for(var h=Gg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.F=new Hg(Eg(h[k]),d),Dg("_gaexp",a.toString(),a.aa,h[k],c)))return!0;return!1},Kg=function(a){for(var b=a.F.f,c=a.F.j,d=Ka("_gaexp"),e=[],f=0;f<d.length;f++){var g=Sg(a,d[f]);g&&e.push(g)}Lf(e,
function(a,d){var e=a.F,f=d.F;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.F=0<e.length?e[0].F:new Hg(b,c);for(f=e.length-1;0<=f;f--)Og(a,Pg(e[f]))},Sg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ha(e[0]);if(0!=f.length){var g=2==e.length?Ha(e[1]):"1";if(tf(f)&&tf(g)){d=new Hg(N(f),N(g));
break a}}}d=void 0}if(d){for(var h=new Jg(d,a.ja,a.aa),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!tf(m[1]))return;Ng(h,m[0],new Ig(m[2],N(m[1])))}}return h}}};var _f=function(a){var b=String(Q("gtm.referrer")||M.referrer);if(!b)return b;var c=ba(b);return b};_f.a="f";_f.b=["google"];var Ea=function(a){var b=w.location,c;(c=a[mc]?a[mc]:Q("gtm.url"))&&(b=ba(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Yb]&&(f=aa(b,a[Yb],a[xe],a[wc],a[ke]));return f},_u=Ea;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[yb])==String(a[S])};_eq.a="eq";_eq.b=["google"];var Na=new String("undefined"),eh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Na?b:a[d]);return c.join("")}};eh.prototype.toString=function(){return this.resolve("undefined")};eh.prototype.valueOf=eh.prototype.toString;var fh={},gh=function(a,b){var c=Hf++;fh[c]=[a,b];return c},hh=function(a){var b=a?0:1;return function(a){var c=fh[a];if(c&&P(c[b]))c[b]();fh[a]=void 0}};var ih=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},jh=function(a,b){return a<b?-1:a>b?1:0};var kh;a:{var lh=db.navigator;if(lh){var mh=lh.userAgent;if(mh){kh=mh;break a}}kh=""}var X=function(a){return-1!=kh.indexOf(a)};var nh=function(){X("iPod")},oh=function(){return X("iPhone")&&!X("iPod")&&!X("iPad")};var ph=function(a){ph[" "](a);return a};ph[" "]=function(){};var rh=function(a,b){var c=qh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var sh=X("Opera"),th=X("Trident")||X("MSIE"),uh=X("Edge"),vh;if(vh=X("Gecko"))vh=!(-1!=kh.toLowerCase().indexOf("webkit")&&!X("Edge"));var wh=vh&&!(X("Trident")||X("MSIE"))&&!X("Edge"),xh=-1!=kh.toLowerCase().indexOf("webkit")&&!X("Edge");xh&&X("Mobile");X("Macintosh");X("Windows");X("Linux")||X("CrOS");var yh=db.navigator||null;yh&&(yh.appVersion||"").indexOf("X11");X("Android");oh();X("iPad");nh();oh()||X("iPad")||nh();var zh=function(){var a=db.document;return a?a.documentMode:void 0},Ah;
a:{var Bh="",Ch=function(){var a=kh;if(wh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(uh)return/Edge\/([\d\.]+)/.exec(a);if(th)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(xh)return/WebKit\/(\S+)/.exec(a);if(sh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ch&&(Bh=Ch?Ch[1]:"");if(th){var Dh=zh();if(null!=Dh&&Dh>parseFloat(Bh)){Ah=String(Dh);break a}}Ah=Bh}
var Eh=Ah,qh={},Fh=function(a){return rh(a,function(){for(var b=0,c=ih(String(Eh)).split("."),d=ih(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=jh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||jh(0==k[2].length,0==l[2].length)||jh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Gh;
var Hh=db.document;Gh=Hh&&th?zh()||("CSS1Compat"==Hh.compatMode?parseInt(Eh,10):5):void 0;var Ih;if(!(Ih=!wh&&!th)){var Jh;if(Jh=th)Jh=9<=Number(Gh);Ih=Jh}Ih||wh&&Fh("1.9.1");th&&Fh("9");var Ya=function(a,b){var c="";th&&!Kh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Lh)a.srcdoc=d;else if(Mh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Nh(a,d)},Lh=xh&&"srcdoc"in document.createElement("iframe"),Mh=wh||xh||th&&Fh(11),Nh=function(a,b){th&&Fh(7)&&!Fh(10)&&6>Oh()&&Ph(b)&&(b=Qh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};th&&!Kh(a)?Rh(a,c):c()},Oh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Kh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{ph(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Sh=0,Rh=function(a,b){var c="goog_rendering_callback"+Sh++;db[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Ph=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Qh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Uh=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=Uh(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=M.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,Sa(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);Uh(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(l){x(d)}}};var Wh=function(a,b,c){if(M.body){var d=
a[fd];d instanceof eh&&(d=d.resolve(gh(b,c)),b=rf);if(a[gf])try{Ya(ja(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),x(b)}catch(e){x(c)}else a[jf]?Vh(d,b,c):Uh(M.body,$a(d),b,c)()}else w.setTimeout(function(){Wh(a,b,c)},200)},_html=Wh;_html.a="html";_html.b=["customScripts"];
var hi=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=ei(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=fi(f,g);gi(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},ii=null,ei=function(a){if(ii)return ii;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return ii=
c}0==a.styleSheets.length&&a.createStyleSheet();return ii=a.styleSheets[0]},fi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},gi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var pi={},qi=void 0,ri=function(a){var b=pi[a];b||(b={id:a,v:[],W:0,Ia:null,za:void 0,Da:!1},pi[a]=b);qi=b},ti=function(a,b,c,d){var e=qi;if(!ug||!e)return!1;var f={id:e.id+":"+e.v.length,eb:b,U:[],Za:c,G:a,ua:0,sa:d||null,Na:0,V:!1};e.v.push(f);null===a?(f.V=!0,b(null)):si(e);return!0},ui=function(a){var b=hi(a,"visibility","hidden",!0);return function(){P(b)&&b.apply();b=null}},vi=function(a,b,c,d){var e=b;if(!Va){var f=ui(a.A);Wa.push(f);e=function(a,c){var d=b(a,c);f();return d}}return ti(a,e,
c,d)},si=function(a){if(!a.Da){for(var b=a.W;b<a.v.length;b++){var c=a.v[b],d=b==a.W;if(!c.V&&!wi(d,c))break;c.V&&d&&a.W++}a.v.length>a.W?(a.Ia||(a.Ia=w.setTimeout(function(){a.Ia=null;si(a)},80)),Va||a.za||(a.za=function(){x(function(){si(a)})},O(M,"DOMContentLoaded",a.za))):xi(a)}},xi=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.G)for(var d=Fa(c.G.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(yi(f,c.id),c.U.push(zi(f,c.id)))}}},wi=
function(a,b){var c=[];if(b.G){var d=Ai(b.G,b.id),e=null;b.sa&&(e=Ai(b.sa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!Va&&(null===b.sa.o||b.Na+c.length<b.sa.o)))break;c.push({element:g,Hb:h})}}if(!Va&&b.Za&&(!a||null==b.G.o||b.G.o!=b.ua+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].Hb,p;b.ua++;yi(l,b.id);m&&(b.Na++,p=b.id+"-t",yi(m,p));var r=b.eb(l,m);P(r)&&b.U.push(r);b.U.push(zi(l,b.id));m&&p&&b.U.push(zi(m,p))}if(b.G.o&&
b.G.o==b.ua||Va)b.V=!0;return!0},yi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},zi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ai=function(a,b){for(var c=Fa(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.D&&!Bi(f))break;d.push(f)}}return d},Bi=function(a){if(Va)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var la,Ci,Di,ta=/(Firefox\D28\D)/g.test(Nf.userAgent),Fi=function(a,b){return function(c){c=c||w.event;var d=xa(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=ya(d,["a","area"]),e=!d||!d.href||Ei(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?la:Di;if(c.defaultPrevented||!1===c.returnValue||c.X&&c.X()){if(d){var g={simulateDefault:!1},h=na(f,["wnc","nwnc"]);h&&pa(a,d,g,f.wt,h)}}else{if(d){var g={},k,l=na(f,["wnc",
"nwnc","nwc","wc"]);(k=pa(a,d,g,f.wt,l))||(qa(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ta;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=va(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},pa=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||ua(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";
g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Gi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Hi(b);g.eventTimeout=f;g.eventCallback=Ii(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ca(g)},Hi=
function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},sa=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},va=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Nf.userAgent),e=sa(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=w.frames&&w.frames[f]||w[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+H().getTime(),b.targetWindow=w.open("",b.targetWindowName));break;default:d&&!w.frames[e]?(b.simulateDefault=!1,c=!0):(w.frames[e]||(b.targetWindowName=e),b.targetWindow=w.frames[e]||w.open("",e))}return c},Gi=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||H().getTime(),500>H().getTime()-c&&w.setTimeout(Gi(a,b,c),25)))}},Ii=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);M.gtmSubmitFormNow=!0;ra(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||H().getTime(),500>H().getTime()-c&&w.setTimeout(Ii(a,b,c),25)}},na=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Ji=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},qa=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Ki.length;c++)if(a.passingRules[c]){var d=Li[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Ki[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},Ca=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(M.gtmHasClickListenerTag)return;M.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=xa(a);b&&pa("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Ci&&(Ci=Wf(M.location));Ji(Di,b||!1,c||!1,d,e);if(M.gtmHasLinkClickListenerTag)return;
M.gtmHasLinkClickListenerTag=!0;f="click";g=Fi(a,b||!1);break;case "FORM_SUBMIT":Ji(la,b||!1,c||!1,d,e);if(M.gtmHasFormSubmitListenerTag)return;M.gtmHasFormSubmitListenerTag=!0;f="submit";g=Fi(a,b||!1);break;default:return}O(M,f,g,h)},Ei=function(a){if(!Ci)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ba(a);return Ci==Wf(c)},ra=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
M.gtmFormElementSubmitter||(M.gtmFormElementSubmitter=M.createElement("form"));return M.gtmFormElementSubmitter.submit.call?M.gtmFormElementSubmitter.submit:a.submit};var Ra=function(a,b){var c=b||db,d=c.onerror,e=!1;xh&&!Fh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,Sa:h,Xb:k,error:l});return e}};var Jj=24,Kj=[],Lj=[],Mj=[],Nj=new Bf,Oj=[],Z=[],Ki=[],Li=[],Pj=function(){this.L=[]};Pj.prototype.set=function(a,b){this.L.push([a,b]);return this};Pj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.L.length;d++){var e=Qj(this.L[d][0],a,b),f=Qj(this.L[d][1],a,b);c[e]=f}return c};var Rj=function(a){this.index=a};Rj.prototype.resolve=function(a,b){var c=Mj[this.index];if(c&&!b(c)){var d=c[kd];if(a){if(a.get(d))return;a.set(d,!0)}c=Qj(c,a,b);a&&a.set(d,!1);return Cf(c)}};
var _M=function(a){return new Rj(a)},Sj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Qj(Kj[a[f]],b,c);g===Na&&(e=!0);d.push(g)}return e?new eh(d):d.join("")}},_T=function(a){return new Sj(arguments)},Tj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Qj(a[0],c,d);if(a[0]instanceof Rj&&b(8)&&b(16)){if(e===Na)return e;var f=Oa();Nj.set(f,e);return'google_tag_manager["GTM-T6RZMX"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Tj(arguments)},Uj=function(a,b){this.w=a;this.ra=b},_R=function(a,b){return new Uj(a,b)},Qj=function(a,b,c){var d=a;if(a instanceof Rj||a instanceof Pj||a instanceof Sj||a instanceof Tj)return a.resolve(b,c);if(!(a instanceof Uj))if(za(a))for(var d=
[],e=0;e<a.length;e++)d[e]=Qj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Qj(a[f],b,c))}return d},Vj=function(a,b){var c=b[a],d=c;if(c instanceof Rj||c instanceof Tj||c instanceof Sj||c instanceof Uj)d=c;else if(za(c))for(var d=[],e=0;e<c.length;e++)d[e]=Vj(c[e],b);else if("object"==typeof c){var d=new Pj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Vj(c[f],b))}return d},Xj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=Kj[e[1]]);if(1==a)for(var f=Wj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Lj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Wj(e[g]);3==a&&(c[d]=Kj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Kj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Wj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Jj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Yj=function(a,b,c){a.push.apply(a,Xj(b,c))};
var jg=function(){},gk=function(a){},mg=function(){},hk=function(a){},ik=function(a,b){},jk=function(a,b){},kg=function(a){};var kk,lk;var vk=function(a){return function(){}},wk=function(a){return function(){}};var xk=function(a){var b=this;this.g=a;this.complete=this.Wa=!1;this.qa=[];this.la=[];this.S=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||Gf(b.qa);Kf(b,1);if(lb[a])for(var e=0;e<lb[a].length;e++)lb[a].shift().S()};this.R=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
Gf(b.la);Kf(b,2);if(lb[a])for(var e=0;e<lb[a].length;e++)lb[a].shift().R()};this.B=rf},yk=function(a,b){a.qa.push(b)},zk=function(a,b){a.la.push(b)},Ak=function(a){this.M=[];this.Ga=[];this.Pa={};this.ya=[];this.Y=0;this.Va={};this.Xa={};this.Ha={};this.event=a};Ak.prototype.addListener=function(a){this.ya.push(a)};
var Bk=function(a,b,c,d,e,f){if(!c.complete){a.M[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=za(d)?d.slice():["or",d];e=za(e)?e.slice():[e];f=za(f)?f.slice():[f];a.Pa[b]=d;a.Va[b]=0<e.length;a.Xa[b]=0<f.length;a.Y++;var g=function(){0<a.Y&&a.Y--;0<a.Y||Gf(a.ya)};yk(c,g);zk(c,g)}},Ck=function(a,b,c){a.M[b]&&(yk(a.M[b],function(){c(b,!0)}),zk(a.M[b],function(){c(b,!1)}))},Dk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Uj&&a[g].w===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Hk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Ek(h,b,a);if(f=g){var k=Fk(b,!0);0<k.length&&e(k[0].w);c.push(f);var l=Fk(b,!1);0<l.length&&e(l[0].w)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Fk(g.g,!0);if(0<h.length){var k=c[f-1],l=Gk(g);yk(k,l);0==h[0].ra&&zk(k,l)}var m=Fk(g.g,!1);0<m.length&&(l=Gk(c[f+1]),yk(g,l),0==m[0].ra&&zk(g,l))}a.Ga.push(c)}},Fk=function(a,b){var c=b?ue:Le,d=Z[a],e=void 0===d[c]?[]:d[c];return za(e)?e:[e]},Gk=function(a){return function(){a.B()}},Jk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Fk(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=Fk(a,!1);0<c.length&&f(c[0].w)};
f(d.g);b[d.g]=e}Ik(a,b);return b},Ik=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<uf(b[e],d)){delete b[d];break}}};var Lk=function(a,b){return function(){a[bd]=b.S;a[cd]=b.R;var c=b.g,d=b.s&&b.s.Ha[c],e=kb[c]&&kb[c].state,f=d?void 0!==d:b.Wa||b.Yb,g=kb[c]&&kb[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){Kf(b,0);var l=b.s?b.s.event:void 0;a=Kk(a,l?l.c:tg());if(l){var m=a;ik(l,c)}Cf(a,b.S,b.R)}else h&&0==e||k&&0==d?lb[c].push(b):h&&1==e||k&&1==d?b.S():b.R()}},Kk=function(a,b){a=Qj(a,new Bf,b);return a},Ek=function(a,b,c){var d=new xk(b);d.s=c;yk(d,vk(a));zk(d,wk(a));d.B=Lk(a,d);return d};var Ok=!1,Pk=!1;var _sp=function(a,b,c){q("//www.googleadservices.com/pagead/conversion_async.js",function(){var d=w.google_trackConversion;P(d)?d({google_conversion_id:a[V],google_conversion_label:a[sd],google_custom_params:a[nc]||{},google_remarketing_only:!0,onload_callback:b})||c():c()},c)};_sp.a="sp";_sp.b=["google"];var Sk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Oj[b]&&Qj(Oj[b],new Bf,c),e=d;if(d)if(d[xb]&&za(d[S]))for(var f=d[S],e=!1,g=0;!e&&g<f.length;g++)d[S]=f[g],e=Cf(d);else e=Cf(d);a[b]=[e,d]}return a[b]}},fk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.P(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.P(e[d],a.c)[0])return!1;return!0},Tk=!1,eg=function(a,b,c,d){switch(b){case "gtm.js":if(Tk)return!1;Tk=!0;break;case "gtm.sync":if(Q("gtm.snippet")!=ib)return!1}Q("tagTypeBlacklist");
for(var e={id:a,name:b,ha:c||rf,fa:Wj(),pa:Wj(),P:Sk(),c:tg()},f=[],g=0;g<Ki.length;g++)if(fk(e,Ki[g])){f[g]=!0;for(var h=e,k=Ki[g],l=k[1],m=0;m<l.length;m++)h.fa[l[m]]=!0;for(var p=k[3],m=0;m<p.length;m++)h.pa[p[m]]=!0}else f[g]=!1;ik(e);var u=[];for(var y=0;y<Jj;y++)if(e.fa[y]&&!e.pa[y])if(e.c(Z[y])){}else{u[y]=Z[y];}e.T=u;for(var t=new Ak(e),z=0;z<Jj;z++)if(e.fa[z]&&!e.pa[z])if(e.c(Z[z])){}else{var D=e.T[z],B=Ek(D,z,t);Bk(t,z,B,D[yc],D[ue],D[Le]);if(D[mb])break}t.addListener(e.ha);for(var A=[],
E=0;E<t.M.length;E++){var I=t.M[E];if(I){var C=t.Pa[E],F=t.Va[E],K=t.Xa[E];if(0!=C.length||F||K){if(0<C.length)for(var U=Dk(C,I.B),L=0;L<C.length;L++)C[L]instanceof Uj&&C[L].w!=E&&Ck(t,C[L].w,U);(F||K)&&Hk(t,E)}else A.push(E)}}for(E=0;E<A.length;E++)t.M[A[E]].B();for(E=0;E<t.Ga.length;E++){for(var Aa=t.Ga[E],ha=void 0,T=Aa,ma=[],ub=0;ub<T.length;ub++){var bb=T[ub],Tb=bb.g,Jf=kb[Tb],vd=Jf.firingOption;0!=vd&&(1==vd&&void 0!==bb.s.Ha[Tb]||2==vd&&void 0!==Jf.state)&&ma.push(bb)}var wd=Jk(ma);for(ha in wd)if(wd.hasOwnProperty(ha)){for(var xd=
void 0,lj=void 0,od=wd[ha],gl=od[0],nj=od[od.length-1],oj,La=0;La<T.length;La++){var pd=T[La];!xd&&pd.g==gl&&0<La&&(xd=T[La-1]);pd.g==nj&&La<T.length-1&&(lj=T[La+1]);if(-1<uf(od,pd.g))if(oj=T.splice(La,1)[0],pd.g==nj)break;else La--}if(oj){var pj=Number(ha),oa=xd,wf=lj;if(oa){var hl=oa.qa[0],il=oa.la[0],qj=oa;qj.qa=[];qj.la=[];yk(oa,hl);zk(oa,il)}if(oa&&wf){var xf=Gk(wf);yk(oa,xf);var yf=Fk(oa.g,!1);0<yf.length&&yf[0].w!=pj&&0==yf[0].ra&&zk(oa,xf);var zf=Fk(wf.g,!0);0<zf.length&&zf[0].w!=pj&&0==zf[0].ra&&
zk(oa,xf)}}}0<Aa.length&&Aa[0].B()}0<t.Y||Gf(t.ya);d&&P(d)&&d({passingRules:f,resolvedTags:e.T});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var tj in e.T)if(e.T.hasOwnProperty(tj)){var uj=e.T[tj],Af;if(!(Af=void 0==uj[kd])){var vj=uj[kd];Af=!("function"!=typeof String.prototype.startsWith?0===vj.indexOf("_implicit"):vj.startsWith("_implicit"))}if(Af)return!0}return!1};var Uk={macro:function(a){if(Nj.contains(a))return Nj.get(a)}};Uk.dataLayer=$f;Uk.onHtmlSuccess=hh(!0);Uk.onHtmlFailure=hh(!1);Uk.callback=function(a){cb.hasOwnProperty(a)&&P(cb[a])&&cb[a]();delete cb[a]};Uk.jb=function(){var a=w.google_tag_manager;a||(a=w.google_tag_manager={});a["GTM-T6RZMX"]||(a["GTM-T6RZMX"]=Uk);Ta=a};(function(){var a=function(a){var b=R("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Di=a("linkClickMap");la=a("formSubmitMap")})();
Kj.push.apply(Kj,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1773929_2147479553',_sp,true,'956542766','',1,_html,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e!function(b,e,f,g,a,c,d){b.fbq||(a\x3db.fbq\x3dfunction(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq\x3da),a.push\x3da,a.loaded\x3d!0,a.version\x3d\x222.0\x22,a.queue\x3d[],c\x3de.createElement(f),c.async\x3d!0,c.src\x3dg,d\x3de.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\x22script\x22,\x22//connect.facebook.net/en_US/fbevents.js\x22);fbq(\x22init\x22,\x22417778941754366\x22);fbq(\x22track\x22,\x22PageView\x22);\x3c/script\x3e\n\x3cnoscript\x3e\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none\x22 src\x3d\x22https://www.facebook.com/tr?id\x3d417778941754366\x26amp;ev\x3dPageView\x26amp;noscript\x3d1\x22\x3e\x3c/noscript\x3e\n',2,'\x3cscript data-gtmsrc\x3d\x22//platform.twitter.com/oct.js\x22 type\x3d\x22text/gtmscript\x22\x3e\x3c/script\x3e\n\x3cscript type\x3d\x22text/gtmscript\x22\x3etwttr.conversion.trackPid(\x22nu4jt\x22,{tw_sale_amount:0,tw_order_quantity:0});\x3c/script\x3e\n\x3cnoscript\x3e\n\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none;\x22 alt\x3d\x22\x22 src\x3d\x22https://analytics.twitter.com/i/adsct?txn_id\x3dnu4jt\x26amp;p_id\x3dTwitter\x26amp;tw_sale_amount\x3d0\x26amp;tw_order_quantity\x3d0\x22\x3e\n\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none;\x22 alt\x3d\x22\x22 src\x3d\x22//t.co/i/adsct?txn_id\x3dnu4jt\x26amp;p_id\x3dTwitter\x26amp;tw_sale_amount\x3d0\x26amp;tw_order_quantity\x3d0\x22\x3e\n\x3c/noscript\x3e',3,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=Vj(c,a);return b}());Yj(Lj,0,"4:0,4:1,7:2,0:3,1:4,4:6,8:7,6:8,3:9,9:10,4:11,5:12,9:13,5:14,9:15,4:16,7:17,7:18,2:19,7:20,2:21,4:22,7:23,7:24");Yj(Mj,1,"G,AAY,AAoB,AAIG,AAAY,CAAg");Yj(Oj,1,"Z");Yj(Z,1,"gP,AxB,ARG");Yj(Ki,2,"B:H::");Yj(Li,4,"5.5.5:");for(var Vk=0;Vk<Z.length;Vk++){var Wk=Z[Vk],Xk=1;Wk[Sd]?Xk=2:Wk[cf]&&(Xk=0);kb[Vk]={firingOption:Xk,state:void 0};lb[Vk]=[]}Uk.jb();
(function(a){})("async");
(function(){var a=R("dataLayer",[]),b=R("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};Wa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Tf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(fg.push.apply(fg,b);300<this.length;)this.shift();return ng()};fg.push.apply(fg,a.slice(0));x(og)})();var el=w;
if("interactive"==M.readyState&&!M.createEventObject||"complete"==M.readyState)Pf();else{O(M,"DOMContentLoaded",Pf);O(M,"readystatechange",Pf);if(M.createEventObject&&M.documentElement.doScroll){var fl=!0;try{fl=!el.frameElement}catch(a){}fl&&Rf()}O(el,"load",Pf)}"complete"===M.readyState?Uf():O(w,"load",Uf);
(function(a){})("async");(function(){})();var _vs="res_ts:1452526668719000,srv_cl:144417228,ds:live,cv:3";
})()
